version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8003:8003"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py wait_for_db && 
      python manage.py migrate && 
      python manage.py init_admin &&
      python manage.py runserver 0.0.0.0:8003"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=p455WORDC#
      - DB_PORT=5432
      - DJANGO_SUPERUSER_PASSWORD=p455WORDC#
      - DJANGO_SUPERUSER_USERNAME=django_admin
      - DJANGO_SUPERUSER_EMAIL=django_admin@gmail.com
      - DJANGO_SECRET_KEY=rnf554@8_nd(99o)s3d(q)lg3dgi5@jp=hn&8(dwrp-ya+09&i
      - DEBUG=True
      - CORS_ORIGIN_ALLOW_ALL=True
      - CORS_ALLOW_CREDENTIALS=False
      - CORS_ORIGIN_WHITELIST=http://localhost, http://0.0.0.0, http://127.0.0.1
      - SECURE_SSL_REDIRECT=False
      - SESSION_COOKIE_SECURE=False
      - CSRF_COOKIE_SECURE=False
      - LANGUAGE_CODE=en-us
      - TIME_ZONE=Europe/Warsaw
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p455WORDC#